# Docker Compose (v2)

version: "2"
services:
  appsvc:
    extends:
      file: docker-compose.base.yml
      service: web
    build:
      context: docker/images/appsvc
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - http_proxy=${HTTP_PROXY:-}
        - https_proxy=${HTTP_PROXY:-}
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTP_PROXY:-}
        - NO_PROXY=hub,${NO_PROXY:-}
        - no_proxy=hub,${NO_PR
    volumes:
      - ./docker/conf/drupal/settings.php:/var/www/html/sites/default/settings.php:ro
      - files_data:/var/www/html/sites/default/files
      - files_private_data:/var/www/files_private

volumes:
  db_data:
  files_data:
  files_private_data:
