# Docker Compose (v2)

version: "2"
services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web

  cli:
    extends:
      file: docker-compose.base.yml
      service: cli

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx

  db:
    extends:
      file: docker-compose.base.yml
      service: ${DB_TYPE:-mysql}

  hub:
    extends:
      file: docker-compose.base.yml
      service: hub

  firefox:
    extends:
      file: docker-compose.base.yml
      service: firefox

volumes:
  db_data:
  files_data:
  files_private_data:
