# Docker Compose (v2)

version: "2"
services:
  web:
    build:
      context: docker/images/dev
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
        - NO_PROXY=hub,${NO_PROXY}
        - no_proxy=hub,${NO_PROXY}
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}
    volumes:
      - .:/var/www
    depends_on:
      - db
    ports:
      - "9000"
    container_name: ${DOCKER_NAME}_web

  cli:
    build:
      context: docker/images/ci
      args:
        - BASE_IMAGE=${BASE_IMAGE}
    entrypoint: ["/bin/sleep", "3650d"]
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - NO_PROXY=hub,${NO_PROXY}
      - no_proxy=hub,${NO_PROXY}
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - web
    container_name: ${DOCKER_NAME}_cli

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - files_private_data:/var/www/files_private
    ports:
      - "3308:3306"
    container_name: ${DOCKER_NAME}_db
    command: mysqld --max_allowed_packet=32M

  nginx:
    build:
      context: docker/images/nginx
      args:
        - BASE_IMAGE=${BASE_IMAGE}
    volumes:
      - ./html:/var/www/html
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always
    container_name: ${DOCKER_NAME}_nginx

  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
    depends_on:
      - db
      - web
    container_name: ${DOCKER_NAME}_hub

  firefox:
    image: selenium/node-firefox:2.53.1
    depends_on:
      - db
      - web
      - hub
    container_name: ${DOCKER_NAME}_firefox
    environment:
      HUB_PORT_4444_TCP_ADDR: hub

  varnish:
    build:
      context: docker/images/varnish
    volumes:
      - ./docker/conf/varnish/default.vcl:/etc/varnish/default.vcl:ro
      - ./docker/conf/varnish/splash.html:/etc/varnish/splash.html:ro
    ports:
      - "80:80"
    depends_on:
      - nginx
    restart: always
    container_name: ${DOCKER_NAME}_varnish

volumes:
  db_data:
  files_data:
  files_private_data:
